---
# create stack - ansible-playbook -i hosts ansible_build_cluster.yaml
# delete stack - ansible-playbook -i hosts ansible_build_cluster.yaml -e "state=absent"

- hosts: localhost
  connection: local

  vars:
  - instance_state: "present"

  tasks:
  - set_fact: state=present
    when: state is undefined
  - name: create/delete cloudformation stack for openshift origin
    cloudformation:
      stack_name: "{{ stack_name }}"
      state: "{{ state }}"
      region: "{{ region }}"
      template: "cft/openshift_cluster.yaml"
      template_parameters:
        KeyName: "{{ key_name }}"
        InstanceType: "{{ instance_type }}"
        AmiId: "{{ ami_id }}"
      tags:
        Stack: cft
